<?php

/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright Copyright (c) 2020 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.integracommerce.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace Mycostum\IntegraCommerce\Block\Adminhtml\Sales\Order\Shipment\Marketplace\Field;

use Magento\Framework\View\Element\Html\Select;

class Channel extends Select
{
    /**
     * Set name
     * @param string $name
     */
    public function setInputName($name)
    {
        $this->setName($name);
        return $this;
    }
}
