<?php
/**
 * IntegraCommerce Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  IntegraCommerce
 * @package   Mycostum_IntegraCommerce
 *
 * @copyright Copyright (c) 2018 B2W Digital - IntegraCommerce Platform.
 *
 * Access https://ajuda.integracommerce.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace Mycostum\IntegraCommerce\Controller\Adminhtml\Customer\Attributes\Mapping;

use Mycostum\IntegraCommerce\Api\CustomerAttributeMappingRepositoryInterface;
use Mycostum\IntegraCommerce\Helper\Context as HelperContext;
use Magento\Backend\App\Action\Context;

class Optionsrenderer extends AbstractMapping
{
    public function __construct(
        Context $context,
        HelperContext $helperContext,
        CustomerAttributeMappingRepositoryInterface $customerAttributeMappingRepository
    )
    {
        parent::__construct($context, $helperContext, $customerAttributeMappingRepository);
    }

    /**
     * @return \Magento\Framework\View\Result\Page
     */
    public function execute()
    {
        $this->_view->loadLayout();
        $this->_view->renderLayout();
    }
}
