<?php
/**
 * BSeller Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  ${MAGENTO_MODULE_NAMESPACE}
 * @package   ${MAGENTO_MODULE_NAMESPACE}_${MAGENTO_MODULE}
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br)
 *
 * Access https://ajuda.integracommerce.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace Mycostum\IntegraCommerce\Integration\Transformer\Catalog;

use Mycostum\IntegraCommerce\Integration\Transformer\AbstractTransformer;

use Mycostum\IntegraCommerce\Helper\Catalog\Product\Attribute\Mapping as AttributeMappingHelper;
use Mycostum\IntegraCommerce\Helper\Catalog\Product as ProductHelper;
use Mycostum\IntegraCommerce\Helper\Eav\Option as EavOptionHelper;
use Mycostum\IntegraCommerce\Helper\Catalog\Product\Attribute as AttributeHelper;
use Magento\Catalog\Helper\ImageFactory;
use Mycostum\IntegraCommerce\Integration\Context;
use Mycostum\IntegraCommerce\Model\Config\IntegracommerceAttributes\Data;
use Magento\CatalogInventory\Model\StockState;

abstract class AbstractProduct extends AbstractTransformer
{
    
    /** @var StockState */
    protected $stockState;

    /** @var  \Magento\CatalogInventory\Api\StockRegistryInterface $stockRegistry */
    protected $stockRegistry;
    
    /** @var Data */
    protected $integracommerceConfig;
    
    /** @var ProductHelper */
    protected $productHelper;
    
    /** @var ImageFactory */
    protected $imageHelperFactory;
    
    /** @var AttributeHelper */
    protected $attributesHelper;
    
    /** @var AttributeMappingHelper */
    protected $attributeMappingHelper;
    
    /** @var EavOptionHelper */
    protected $eavOptionHelper;
    
    public function __construct(
        Context $context,
        StockState $stockState,
        ProductHelper $productHelper,
        ImageFactory $imageHelperFactory,
        AttributeHelper $attributesHelper,
        AttributeMappingHelper $attributeMappingHelper,
        EavOptionHelper $eavOptionHelper,
        Data $integracommerceConfig,
        \Magento\CatalogInventory\Api\StockRegistryInterface $stockRegistry
    ) {
        parent::__construct($context);
        
        $this->stockState             = $stockState;
        $this->productHelper          = $productHelper;
        $this->imageHelperFactory     = $imageHelperFactory;
        $this->attributesHelper       = $attributesHelper;
        $this->attributeMappingHelper = $attributeMappingHelper;
        $this->eavOptionHelper        = $eavOptionHelper;
        $this->integracommerceConfig           = $integracommerceConfig;
        $this->stockRegistry          = $stockRegistry;
    }
    
    
    /**
     * @param \Magento\Catalog\Model\Product $product
     *
     * @return $this|array
     */
    protected function getProductGalleryImages(\Magento\Catalog\Model\Product $product)
    {
        $images = [];

        /** @var array $gallery */
        $gallery = $product->getMediaGalleryEntries();

        if (!$gallery || !count($gallery)) {
            return $images;
        }
        

        /** @var \Magento\Catalog\Model\Product\Gallery\Entry $galleryImage */
        foreach ($gallery as $galleryImage) {
            /**
             * If the same instance of the helper is used the images will be all the same.
             * This helper does not seem to be transient.
             *
             * @var \Magento\Catalog\Helper\Image $helper
             */
            $helper = $this->imageHelperFactory->create();
            $url    = $helper->setImageFile($galleryImage->getFile())->getUrl();
    
            $images[]['url'] = $url;
        }
    
        return $images;
    }
}
