<?php
/**
 * IntegraCommerce Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  IntegraCommerce
 * @package   Mycostum_IntegraCommerce
 *
 * @copyright Copyright (c) 2018 B2W Digital - IntegraCommerce Platform.
 *
 * Access https://ajuda.integracommerce.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace Mycostum\IntegraCommerce\Helper\Customer\Attribute;

use Mycostum\IntegraCommerce\Helper\Context;
use Mycostum\IntegraCommerce\Model\ResourceModel\Customer\Attributes\Mapping\Collection as AttributesMappingCollection;
use Mycostum\IntegraCommerce\Model\ResourceModel\Customer\Attributes\Mapping\Options\Collection as AttributesMappingOptionsCollection;
use Magento\Framework\Registry;

class Mapping
{
    
    /** @var Context */
    protected $context;
    
    /** @var Registry */
    protected $registry;
    
    /** @var array */
    protected $mappedAttributes = [];

    /**
     * Mapping constructor.
     * @param Context $context
     * @param Registry $registry
     */
    public function __construct(
        Context $context,
        Registry $registry
    )
    {
        $this->context  = $context;
        $this->registry = $registry;
    }
    
    
    /**
     * @param string $integracommerceCode
     *
     * @return mixed|null
     */
    public function getMappedAttribute($integracommerceCode)
    {
        $this->initMappedAttributes();
        
        if (isset($this->mappedAttributes[$integracommerceCode])) {
            return $this->mappedAttributes[$integracommerceCode];
        }
        
        return null;
    }
    
    
    /**
     * @return array
     */
    public function getMappedAttributes()
    {
        $this->initMappedAttributes();
        
        return (array) $this->mappedAttributes;
    }
    
    
    /**
     * @return $this
     */
    protected function initMappedAttributes()
    {
        if (empty($this->mappedAttributes)) {
            $this->mappedAttributes = [];
            
            /** @var \Mycostum\IntegraCommerce\Model\Customer\Attributes\Mapping $mappedAttribute */
            foreach ($this->getMappedAttributesCollection() as $mappedAttribute) {
                $this->mappedAttributes[$mappedAttribute->getIntegracommerceCode()] = $mappedAttribute;
            }
        }
        
        return $this;
    }
    
    
    /**
     * @return bool
     */
    public function hasPendingAttributesForMapping()
    {
        return (bool) ($this->getPendingAttributesCollection()->getSize() > 0);
    }
    
    
    /**
     * @return AttributesMappingCollection
     */
    public function getPendingAttributesCollection()
    {
        $key = 'notification_pending_attributes_collection';
        
        if (!$this->registry->registry($key)) {
            /** @var AttributesMappingCollection $collection */
            $collection = $this->getAttributesMappingCollection()
                ->setPendingAttributesFilter();
            
            $this->registry->register($key, $collection, true);
        }
        
        return $this->registry->registry($key);
    }
    
    
    /**
     * @return AttributesMappingCollection
     */
    public function getMappedAttributesCollection()
    {
        $collection = $this->getAttributesMappingCollection()
            ->setMappedAttributesFilter();
        
        return $collection;
    }
    
    
    /**
     * @return AttributesMappingCollection
     */
    public function getAttributesMappingCollection()
    {
        /** @var AttributesMappingCollection $collection */
        $collection = $this->context
            ->objectManager()
            ->create(AttributesMappingCollection::class);
        
        return $collection;
    }

    public function getAttributeMappingOptionMagentoValue($customerAttributesMappingId, $integracommerceCode) {
        /** @var AttributesMappingCollection $collection */
        $collection = $this->context
            ->objectManager()
            ->create(AttributesMappingOptionsCollection::class);

        $collection->addFieldToFilter('customer_attributes_mapping_id', $customerAttributesMappingId)
            ->addFieldToFilter('integracommerce_code', $integracommerceCode);

        return $collection->getFirstItem();
    }
}
