<?php
/**
 * IntegraCommerce Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  IntegraCommerce
 * @package   Mycostum_IntegraCommerce
 *
 * @copyright Copyright (c) 2018 B2W Digital - IntegraCommerce Platform.
 *
 * Access https://ajuda.integracommerce.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace Mycostum\IntegraCommerce\Api;

use Magento\Framework\Api\SearchCriteriaInterface;

interface CustomerAttributeMappingOptionsRepositoryInterface
{
    /**
     * Retrieve all attributes for entity type
     *
     * @param SearchCriteriaInterface $searchCriteria
     *
     * @return mixed
     */
    public function getList(SearchCriteriaInterface $searchCriteria);


    /**
     * @param $mappingId
     *
     * @return mixed
     */
    public function get($mappingId);


    /**
     * @param Data\CustomerAttributeMappingOptionsInterface $mapping
     *
     * @return mixed
     */
    public function save(Data\CustomerAttributeMappingOptionsInterface $mapping);


    /**
     * @param Data\CustomerAttributeMappingOptionsInterface $mapping
     *
     * @return mixed
     */
    public function delete(Data\CustomerAttributeMappingOptionsInterface $mapping);


    /**
     * @param int $mappingId
     *
     * @return mixed
     */
    public function deleteById($mappingId);
}
