<?php
/**
 * IntegraCommerce Platform | B2W - Companhia Digital
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  IntegraCommerce
 * @package   Mycostum_IntegraCommerce
 *
 * @copyright Copyright (c) 2018 B2W Digital - IntegraCommerce Platform.
 *
 * Access https://ajuda.integracommerce.com.br/hc/pt-br/requests/new for questions and other requests.
 */

namespace Mycostum\IntegraCommerce\Model\Customer\Attributes\Mapping;

use Mycostum\IntegraCommerce\Api\Data\CustomerAttributeMappingOptionsInterface;
use Magento\Framework\Model\AbstractModel;
use Mycostum\IntegraCommerce\Model\ResourceModel\Customer\Attributes\Mapping\Options as ResourceModel;

class Options extends AbstractModel implements CustomerAttributeMappingOptionsInterface
{

    /**
     * Initialize resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init(ResourceModel::class);
    }

}
